# Generated by Django 2.2.3 on 2019-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.CharField(max_length=50)),
                ('user', models.CharField(blank=True, max_length=40)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('lead_id', models.CharField(blank=True, max_length=50)),
                ('campaign_id', models.CharField(blank=True, max_length=40)),
                ('vendor_lead_code', models.IntegerField(blank=True)),
                ('source_id', models.CharField(max_length=50)),
                ('list_id', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('length_in_sec', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('status_name', models.CharField(blank=True, max_length=50)),
                ('recording_id', models.CharField(blank=True, max_length=50)),
                ('call_notes', models.CharField(blank=True, max_length=100)),
                ('recording_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
