# Generated by Django 2.2.3 on 2019-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_records',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
