# Generated by Django 2.2.3 on 2019-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20190703_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_records',
            name='call_notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='campaign_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='lead_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='length_in_sec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='list_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='recording_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='recording_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='status_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='vendor_lead_code',
            field=models.IntegerField(null=True),
        ),
    ]
