# Generated by Django 2.2.3 on 2019-07-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20190703_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_records',
            name='mobile_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
