# Generated by Django 2.2.3 on 2019-12-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0007_auto_20190703_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_records',
            old_name='call_notes',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='search_records',
            name='name',
        ),
        migrations.RemoveField(
            model_name='search_records',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='search_records',
            name='vendor_lead_code',
        ),
        migrations.AddField(
            model_name='search_records',
            name='recording_filename',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
