# Generated by Django 2.2.3 on 2019-12-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0008_auto_20191211_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_records',
            old_name='list_id',
            new_name='Badge_ID',
        ),
        migrations.RenameField(
            model_name='search_records',
            old_name='user',
            new_name='User_ID',
        ),
        migrations.RenameField(
            model_name='search_records',
            old_name='recording_id',
            new_name='campaign_name',
        ),
        migrations.RenameField(
            model_name='search_records',
            old_name='email',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='search_records',
            old_name='recording_url',
            new_name='recording_location',
        ),
        migrations.RemoveField(
            model_name='search_records',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='search_records',
            name='status_name',
        ),
        migrations.AddField(
            model_name='search_records',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='search_records',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='lead_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
