# Generated by Django 2.2.3 on 2019-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0009_auto_20191212_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_records',
            name='time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
