# Generated by Django 2.2.3 on 2019-12-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0010_search_records_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_records',
            name='campaign_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
