# Generated by Django 2.2.3 on 2019-12-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0011_auto_20191212_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_records',
            name='Badge_ID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='User_ID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='campaign_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_records',
            name='lead_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
