# Generated by Django 2.2.3 on 2019-12-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0012_auto_20191212_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_records',
            old_name='Badge_ID',
            new_name='badge_id',
        ),
        migrations.RenameField(
            model_name='search_records',
            old_name='User_ID',
            new_name='user_id',
        ),
    ]
